[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

  [dev]
    framework = "#custom"
    command = "npm run dev:webpack"
    targetPort = 8079
    port = 8080
    publish = "build"
    autoLaunch = false